### PR TITLE
Fix panic if channel is meeting is not found

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Fix a `panic` if the meeting for autocomplete and add a log message.

#### Ticket Link
https://community-daily.mattermost.com/core/pl/g5c8dwh5ufrtpprtontzeecnuc

### CODE REVIEW

**Review by jfrerich — APPROVED** [review]

**Review by marianunez — APPROVED** [review]
Thanks @hanzei!

**Comment by DHaussermann** [comment]
@hanzei any thoughts on testing this? Would I need a way to simulate such an error?

**Comment by hanzei** [comment]
@DHaussermann Not really. I don't know what causes the crash, which is why I added the log statement.

**Comment by hanzei** [comment]
@DHaussermann Would you be fine skipping QA review?

**Comment by DHaussermann** [comment]
@hanzei, makes sense to me. As it is there is no functional testing I can do.
LGTM!

**Pull request merged**
