### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
In prep for the `v0.1.0` release, we should fix these dependabot alerts.

image

#### Ticket Link
n/a

### CODE REVIEW

**Review by iomodo — APPROVED** [review]

**Review by hanzei — COMMENTED** [review]
Why is the diff so huge? If there are only two alerts to fix, why do all of these dependencies get updated?

**Comment by jfrerich** [comment]
@hanzei, `package-lock.json` changed considerably after running `npm audit fix`.  

After running `npm install` on `master`, we see the following:
image

After running `npm audit fix` the low severity packages were also updated. 
image

It looks like `Dependabot` only highlights medium and high severity issues, but running `npm audit fix` fixes the low severity dependencies also.

If we prefer only to fix the two dependabot notifications, I can rerun the following and reduce the total number of dependency updates:
* `npm install --save-dev serialize-javascript@3.1.0`
* `npm install --save-dev minimist@0.2.1`

**Comment by hanzei** [comment]
I'm 1/5 to only fix the ones that `Dependabot` reports. We don't have a process for the other ones.

If there is an easy way to fix only these two, I would prefer it, but if there is none, I'm fine with using `npm audit fix`.

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by hanzei** [comment]
It might be fine to skip QA review here, as release testing is coming up soon after.

**Comment by jfrerich** [comment]
agree!  Merging!

**Pull request merged**
