### PR TITLE
Plugin review proposals

### PR DESCRIPTION
**Pull request by jfrerich**
## Summary 

This is a PR with suggested changes discovered during the Plugin Review Process.  The purpose of this 2nd PR is to give both the plugin author and other developers the chance to review changes before pushing into master.

### CODE REVIEW

**Comment by jfrerich** [comment]
Hi @marianunez and @levb. This is a PR that can be used to let the authors and devs see the proposed changes I would make.  Note this is currently a draft PR and I will be making for commits.

**Comment by levb** [comment]
1/5 for merging incrementally

**Comment by marianunez** [comment]
> 1/5 for merging incrementally

@levb Can you explain what you mean by incrementally?

**Comment by levb** [comment]
@marianunez Like, in merge the changes we already have here (once approved), and cut another PR if we need to make more changes.

**Comment by marianunez** [comment]
@levb sounds good. I discussed offline with @jfrerich and I think most of the other changes proposed I will continue on the original PR here https://github.com/mattermost/mattermost-plugin-agenda/pull/2

**Comment by jfrerich** [comment]
@levb, for this plugin, I have created this PR so that @marianunez can review the changes before merging.  This is a little different than the google calendar plugin, where I basically took ownership and merged changes directly.  

@marianunez, if these changes look good for your approval, let's go ahead and approve/merge and I'll create additional PRs for other changes.

**Pull request merged**
